### PR TITLE
fix channel.delete() even more

### PR DESCRIPTION
**Pull request by brakhane**

### CODE REVIEW

**Comment by brakhane** [comment]
sorry :/

**Comment by Fuyukai** [comment]
tfw I wrote that line in state.py in 2016 and it hasn't worked since

**Comment by Fuyukai** [comment]
Honestly impressed with how broken my code is now that somebody other than me uses it

**Comment by brakhane** [comment]
Considering how complex the Discord API and event handling is, I'm actually impressed how few issues I'm having.

**Pull request merged**
