### PR TITLE
Use zlib-stream as compression method

### PR DESCRIPTION
**Pull request by brakhane**
Fixed version of PR #16, I forgot to reset the data stream when a new socket was being opened.

So far my bot ran for 40 minutes without problems, and the total data volume is around 50 KB, so significantly less for 40 minutes than the data volume that was just used for guild member streaming during startup (93KB) previously.

-----

This should significantly increase the compression rate.
On a quick test on a 250 member guild, just the initial member stream data
size was reduced by more than half, from 93 KB to 40 KB.

Using zlib streaming is useful because discord ids are long, and the same
id does seldom appear more than once in a single event. It will however
probably appear in later events, and zlib can then compress the reoccurence.

### CODE REVIEW

**Comment by Fuyukai** [comment]
I feel like perhaps the decompression object should be re-created on a reconnect - feels like if the WS has to reconnect inbetween a compressed packet, it'll re-open with a bunch of junk.

**Comment by brakhane** [comment]
yes, I noticed a few crashes due to decompressobj not being reset, I'm working on it and will update this PR

**For now, do not merge.**

**Comment by brakhane** [comment]
OK, I'm resetting zlib now whenever lomond sends the opening event, which happens after the server closes the socket (due to missed heartbeat for example). This seems to fix the crashes I've seen.

I will monitor my bot closely in the following days, if you hear nothing from me, you can assume that this PR works for me(TM)

**Comment by brakhane** [comment]
Just a quick update, bot has been running stable now for 5 hours, even when I suspended it for minutes so the heartbeat would fail and lomond recreated the connection.

**Comment by brakhane** [comment]
17 hours now without a hitch. So from my perspective, this PR is ready.

**Pull request merged**
